version: '3.0'

networks:
  iot:
    driver: bridge

volumes:
  db-data:
    driver: local


services:
  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - iot
    environment:
      - DB_HOST=postgres:5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
  
  postgres:
    image: "postgres:15.1-alpine"
    networks:
      - iot
    ports:
      - "5437:5432"
    volumes:
      - db-data:/var/lib/postgres/data
    env_file:
      - .env
