create table sensors
(
    id   bigint generated by default as identity primary key,
    name varchar(255) unique not null
);

create table measurements
(
    id        bigint generated by default as identity primary key,
    value     float   not null default 0,
    raining   boolean not null,
    sensor_id bigint,
    constraint fk_sensor_id foreign key (sensor_id) references sensors (id)
);

create table users
(
    id       bigint generated by default as identity primary key,
    username varchar(255) not null unique,
    password varchar(255) not null
)