spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: iot-application

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}/${POSTGRES_DB}

  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: none

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

server:
  port: 8080

security:
  jwt:
    access: 5m
    refresh: 5d
    secret: Z2ZoZGZnaGRmYXNnZmFzZGZlcnR5ZXJ0eWVydGl1dHlpdWtoaixubWIsY2I=